name: 'dbt_practice'
version: '1.0.0'
config-version: 2

profile: 'dbt_practice'

# Path configurations
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Models configuration
models:
  dbt_practice:

    # RAW / SOURCES (no materialization here)
    sources:
      +enabled: true

    # STAGING layer
    staging:
      +materialized: view
      +schema: staging

    # MART layer
    marts:
      +materialized: table
      +schema: marts

      dimensions:
        +materialized: table

      facts:
        +materialized: incremental
        +on_schema_change: sync_all_columns

# Snapshots configuration
snapshots:
  dbt_practice:
    +target_schema: snapshots

# Tests
tests:
  +store_failures: true
  +schema: test_failures

# Seeds (if you add later)
seeds:
  dbt_practice:
    +schema: seeds

# Vars (optional, useful later)
vars:
  timezone: 'UTC'
